version: '3.7'

networks:
  tombspawn:
    name: tombspawn

volumes:
  mysqldb:
    name: mysqldb
  redisdb:
    name: redisdb

services:
  db:
    container_name: mysqldb
    build: docker/mysql/.
    image: mysqldb
    volumes:
      - mysqldb:/var/lib/mysql
    restart: always
    env_file:
      - scripts/local/mysql.env
    networks:
      - tombspawn
    ports:
      - "3306:3306"
  redis:
    container_name: redisdb
    build: docker/redis/.
    image: redisdb
    volumes:
      - redisdb:/data
    restart: always
    networks:
      - tombspawn
    ports:
      - "6379:6379"
  application:
    container_name: application
    depends_on:
      - db
      - redis
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
      dockerfile: Dockerfile
    image: application
    restart: always
    volumes:
      - ${CONF_PATH}:/app/application.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tombspawn
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 3G
        reservations:
          cpus: '0.50'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s