version: '2.4'

networks:
  tombspawn:
    name: tombspawn

volumes:
  mysqldb:
    name: mysqldb
    driver: local
  redisdb:
    name: redisdb
    driver: local
  apkCache:
    name: apkCache
    driver: local

services:
  db:
    container_name: mysqldb
    build: scripts/remote/docker/mysql/.
    image: mysqldb
    volumes:
      - mysqldb:/var/lib/mysql
    restart: always
    env_file:
      - scripts/local/mysql.env
    networks:
      - tombspawn
  redis:
    container_name: redisdb
    build: scripts/remote/docker/redis/.
    image: redisdb
    volumes:
      - redisdb:/data
    restart: always
    networks:
      - tombspawn
  application:
    container_name: application
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    image: application
    restart: always
    volumes:
      - apkCache:/app/temp
      - ./scripts/local/application.json:/app/application.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tombspawn
    ports:
      - "63648:8080"